### ISSUE TITLE
测试集合中点击子集合用例左侧菜单栏不更新

### ISSUE THREAD

**Issue by JSMengLingqi** [xian-crazy/yapi#10]
## 版本号
~ 

## 什么问题
~点击集合用例的文件夹时，在content里点击进入其中一个用例，左侧菜单高亮没有更新，仍显示为用例的文件夹

## 如何复现此问题
~ 

## 什么浏览器
~

**Comment by xian-crazy** [comment]
是个bug，8月底安排处理

**Comment by xian-crazy** [comment]
新版本已经修复了
