### ISSUE TITLE
接口列表 箭头区域也能点击

### ISSUE THREAD

**Issue by daiooo** [xian-crazy/yapi#11]
建议:
接口列表 箭头区域也能点击 (和原版类似)

![image](https://user-images.githubusercontent.com/46855652/63142613-0ad7a500-c01d-11e9-8041-a4c3bc8d00b6.png)

**Comment by xian-crazy** [comment]
交互暂时不影响功能使用，优先级会比较低，最近公司事务比较忙，后续会做优化

**Comment by daiooo** [comment]
> 交互暂时不影响功能使用，优先级会比较低，最近公司事务比较忙，后续会做优化

旧版能点击, 习惯了...

**Comment by BetaGo** [comment]
@daiooo 功能已加，还其他细节优化哟。😁
