### ISSUE TITLE
项目设置中使用swagger同步接口，提示interface_cat validation failed:parent_id:Path'parent_id'is required 

### ISSUE THREAD

**Issue by CNGTZ** [xian-crazy/yapi#12]
## 版本号
~ 
版本: crazy-2019.8.6
## 什么问题
~
项目设置中使用swagger同步接口，提示interface_cat validation failed:parent_id:Path'parent_id'is required 
导入数据时选择swagger方式，同样提示以上错误信息
## 如何复现此问题
~ 

## 什么浏览器
~ 
chrome
## 什么系统（Linux, Windows, macOS）
ubuntu

**Comment by xian-crazy** [comment]
已经修复 请更新回归验证，谢谢！

**Comment by lm93129** [comment]
demo上还有这个问题，请问demo有更新么？
