### ISSUE TITLE
菜单栏箭头问题以及显示用例总数

### ISSUE THREAD

**Issue by JSMengLingqi** [xian-crazy/yapi#2]
## 版本号
~ 1.7

## 什么问题
~1、菜单栏箭头点击按钮不生效
~2、测试集合这里加上显示总用例个数

## 如何复现此问题
~ 

## 什么浏览器
~ chrome

## 什么系统（Linux, Windows, macOS）
Windows

**Comment by xian-crazy** [comment]
问题1.要改树控件和逻辑，属于优化，9月或者10月处理
问题2.会尽快处理

**Comment by xian-crazy** [comment]
箭头点击展开关闭已经实现
用例个数后续优化
