### ISSUE TITLE
配置跨域不如之前用插件稳定

### ISSUE THREAD

**Issue by JSMengLingqi** [xian-crazy/yapi#23]
这边使用的出现两台机器，上午配好浏览器跨域下午就不能用了，而且任何方法都试了都不行，导致测试进程阻塞，严重影响工作效率。目前也未调查出具体原因，之前先还原之前版本了。

**Comment by xian-crazy** [comment]
找到原因了吗？浏览器跨域这个确实是个问题，有得有失吧，我们团队用了半年了，还没遇到过类似的问题，遇到了才好查原因

**Comment by JSMengLingqi** [comment]
https://www.cnblogs.com/yanggl/p/10211930.html
目前个别机子碰到了只能先用这个第三种方式配置。。。但是有点儿麻烦大多数人都不愿意用
