### ISSUE TITLE
Tests中storage无法使用

### ISSUE THREAD

**Issue by hardBeasy** [xian-crazy/yapi#26]
## 版本号
~ 

## 什么问题
Tests中脚本如下：
var opcode=storage.getItem('usercode');

运行报错如下：
Cannot read property 'getItem' of undefined

## 如何复现此问题
~ 

## 什么浏览器
~

**Comment by xian-crazy** [comment]
最近项目比较忙 这个可以支持的 后续抽空添加

**Comment by xian-crazy** [comment]
感谢@betaGo
