### ISSUE TITLE
[建议]接口列表加Method (GET POST PUT ...)

### ISSUE THREAD

**Issue by daiooo** [xian-crazy/yapi#3]
接口列表加Method (GET POST PUT)
![image](https://user-images.githubusercontent.com/46855652/63071902-aef51980-bf53-11e9-9fdd-834f22fde8a4.png)
postman
![image](https://user-images.githubusercontent.com/46855652/63071911-bc120880-bf53-11e9-9b34-2be69ccf90a5.png)

**Comment by xian-crazy** [comment]
比较炫酷，小手一抖就能改，下周搞定

**Comment by xian-crazy** [comment]
和项目组小伙伴交流了下  他们更加关注接口生命周期 也就是接口状态 开发中 已完成 等等
至于接口Method   感觉无所谓是否显示，显示了只是比较炫酷，就暂时不改了
