### ISSUE TITLE
接口设计的字段类型能否添加2个类型：  long timestamp  

### ISSUE THREAD

**Issue by jennyjane** [xian-crazy/yapi#37]
## 版本号
~ 最新版 20191025

## 什么问题
~接口设计的字段类型能否添加2个类型：  long timestamp  
![image](https://user-images.githubusercontent.com/19267219/66819373-7385c400-ef71-11e9-8970-b93d42c0f3ec.png)

## 如何复现此问题
~ 添加接口-编辑请求参数设置和返回数据设置-设置字段的类型

## 什么浏览器
~ chrome

## 什么系统（Linux, Windows, macOS）
Linux

**Comment by BetaGo** [comment]
字段验证是根据json-schema规范来的，目前规范中不支持 long 和 timestamp类型。
[json-schema支持类型](https://json-schema.org/draft/2019-09/json-schema-validation.html#rfc.section.6.1.1)

**Comment by xian-crazy** [comment]
建议按照规范来
