### ISSUE TITLE
yapi每个项目都有动态显示谁做了哪些操作，但是不好查每个接口的历史改动记录，能否给每个接口都显示一个历史改动记录查看入口呢

### ISSUE THREAD

**Issue by jennyjane** [xian-crazy/yapi#47]
## 版本号
 最新版

## 什么问题
yapi每个项目都有动态显示谁做了哪些操作，但是不好查每个接口的历史改动记录，能否给每个接口都显示一个历史改动记录查看入口呢

![image](https://user-images.githubusercontent.com/19267219/67655750-a6c24d00-f98c-11e9-9a8c-298f5d6ecbcf.png)

**Comment by xian-crazy** [comment]
![image](https://user-images.githubusercontent.com/6520452/67655898-294b0c80-f98d-11e9-9e47-599f4c003989.png)
当前有这个功能，不知是否满足你的诉求：在动态中可以输入选择接口，查看指定接口的变更记录

**Comment by jennyjane** [comment]
好像也可以哦，谢谢啦，之前没注意到这里
