### ISSUE TITLE
测试集合这里加上显示总用例个数

### ISSUE THREAD

**Issue by JSMengLingqi** [xian-crazy/yapi#48]

**Comment by xian-crazy** [comment]
@BetaGo  这个请优先处理下

**Comment by BetaGo** [comment]
> @BetaGo 这个请优先处理下

这周会加上，最近有点忙😹

**Comment by JSMengLingqi** [comment]
加油！

**Comment by JSMengLingqi** [comment]
> > @BetaGo 这个请优先处理下
> 
> 这周会加上，最近有点忙😹

没有所有用例数哎。。。而且也没有子文件夹下面的用例数，想统计全部用例只能一个一个点。。。可以优化下不？

**Comment by BetaGo** [comment]
![image](https://user-images.githubusercontent.com/22720510/67824691-1279f680-fb02-11e9-9b7a-4f75ce981b67.png)
最新master分支代码，用例数显示在这里.

**Comment by xian-crazy** [comment]
good job
