### ISSUE TITLE
接口请求时控制台没有显示请求的参数

### ISSUE THREAD

**Issue by a771853580** [xian-crazy/yapi#5]
## 版本号
~ 

## 什么问题
~
1、建议显示请求参数

![image](https://user-images.githubusercontent.com/28817971/63087793-97cf1f80-bf85-11e9-9fcc-41419b58d4b0.png)

## 如何复现此问题
~ 

## 什么浏览器
~

**Comment by xian-crazy** [comment]
会尽快处理

**Comment by BetaGo** [comment]
![image](https://user-images.githubusercontent.com/22720510/66991323-69430180-f0fa-11e9-95df-54cc401df802.png)
加了一个 queryParams 字段来展示get请求的参数，post请求的参数在data字段里.
@a771853580
