### ISSUE TITLE
用例名称超长时显示不全，建议可拖动或tooltip显示全部

### ISSUE THREAD

**Issue by hardBeasy** [xian-crazy/yapi#55]
## 版本号
~ 

## 什么问题
~

## 如何复现此问题
1.用例列表：
![image](https://user-images.githubusercontent.com/49235727/67922582-14b58100-fbe6-11e9-9ca8-e39935cbf41c.png)

2.用例集执行：
![image](https://user-images.githubusercontent.com/49235727/67922623-3ca4e480-fbe6-11e9-84f7-320ea6f61a3b.png)

## 什么浏览器
~

**Comment by xian-crazy** [comment]
@BetaGo   建议树状菜单栏可以 拖动变宽+tooltip 两个功能都有

**Comment by BetaGo** [comment]
最新master分支代码，功能已加
