### ISSUE TITLE
切换用例集和用例时页面乱跳

### ISSUE THREAD

**Issue by hardBeasy** [xian-crazy/yapi#56]
## 版本号
~ 

## 什么问题
~
用例集下用例加载较慢，在点击用例集后，且用例未加载出来时就切换至具体用例，页面在用例集和用例间跳转，刷新才可中止。
## 如何复现此问题
~ 
![flash](https://user-images.githubusercontent.com/49235727/67962978-d6957d00-fc38-11e9-9eea-1b25cf4b28f8.gif)

## 什么浏览器
~

**Comment by hardBeasy** [comment]
现在用例量变多，打开树结构时会非常慢~
@xian-crazy 这个加载问题已经影响使用了，点击用例集或者用例要平均等待十几秒，可不可以优先帮忙看下问题原因呢？感谢~
@BetaGo   非常紧急，求定位，如果需要提供相关内容或验证，请联系qq，微信同号：805675496。。。。

**Comment by hardBeasy** [comment]
目前用例量700+，加载过程中时常报：项目id不能为空，NetWork Error，请问如何排查原因呢
![image](https://user-images.githubusercontent.com/49235727/68098067-9151a380-fef5-11e9-8174-2e3b029a3edc.png)
@BetaGo  另外，也请您看下NetWork Error 的问题，近两天出现很频繁，不知道是不是用例内容多的原因，我在示例工程中创建了很多用例，也同样出现加载慢和NetWork Error的问题。

**Comment by BetaGo** [comment]
> 现在用例量变多，打开树结构时会非常慢~
> @xian-crazy 这个加载问题已经影响使用了，点击用例集或者用例要平均等待十几秒，可不可以优先帮忙看下问题原因呢？感谢~
> @BetaGo 非常紧急，如果定位不了问题可能要无奈放弃了。。。。

排查中。

**Comment by hardBeasy** [comment]
run_script平均每个运行都在1s+，与用例量少时不是一个感觉，一次性运行很多用例时，越到后面，run_script越慢。
![image](https://user-images.githubusercontent.com/49235727/68098834-fe673800-fef9-11e9-9c0f-66e04f93ab88.png)

![image](https://user-images.githubusercontent.com/49235727/68098829-f5766680-fef9-11e9-99df-760517c27048.png)

**Comment by hardBeasy** [comment]
执行完更新执行 up_col 时报错

**Comment by hardBeasy** [comment]
@BetaGo 您好，请问有办法解决么？目前测试过程使用的这个平台，影响蛮大的，非常感谢~

**Comment by BetaGo** [comment]
> @BetaGo 您好，请问有办法解决么？目前测试过程使用的这个平台，影响蛮大的，非常感谢~

**关于用例树加载慢的问题**，后续会尽快改为异步的加载来提高性能；

**关于up_col报错**，看图上的信息，是传参数据量过大，导致了服务端报错。
应该是因为您那里一次测试的接口数量比较多，使最后生成的报告数据量很大，超过了服务端可以接受的最大值；
目前先建议您单个分组进行测试，不要一次性跑太多测试；后续我们会想方案解决。

非常感谢您的使用与建议。

**Comment by hardBeasy** [comment]
好的，急盼解决后继续推广使用~

**Comment by JSMengLingqi** [comment]
> 现在用例量变多，打开树结构时会非常慢~
> @xian-crazy 这个加载问题已经影响使用了，点击用例集或者用例要平均等待十几秒，可不可以优先帮忙看下问题原因呢？感谢~
> @BetaGo 非常紧急，求定位，如果需要提供相关内容或验证，请联系qq，微信同号：805675496。。。。

我们用例量5000多个。。。。要40多秒才能全部显示。

**Comment by BetaGo** [comment]
页面乱跳的问题，master分支代码已修复；
原因是接口请求响应慢，导致数据的正确性出现了问题，最新代码会取消掉无效的请求，保证数据正确性。

关于树结构慢的问题，可以新开个issue单独讨论。

**Comment by hardBeasy** [comment]
赞效率！树结构加载问题已新开issue~
