### ISSUE TITLE
希望能显示所有用例总数

### ISSUE THREAD

**Issue by JSMengLingqi** [xian-crazy/yapi#57]
可以像点击全部接口后会显示全部接口数一样，显示一个全部用例数
![avatar](data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAA9YAAACsCAYAAACeuDSIAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAACmtSURBVHhe7Z3/zx3Vnd/5E5r2p6raJZBqo/4hFT9UVrVKRbUrlQpRJCQ3qssPkCqb7kK2tCjREi9OduVFiBUbilNKtjyEgKU1QRDstYOdAGsH+7EpmGIwD49tbGMDNqdzvszMmTOfMzPnzj3Pc+88r5f0kn3n67lz555z3nNmnnuDAgAAAAAAAICZIVgDAAAAAAAAjIBgDQAAAAAAADACgjUAAAAAAADACAjWAAAAAAAAACMgWAMAAAAAAACMgGANAAAAAAAAMAKCNQAAAAAAAMAICNYAAAAAAAAAIyBYAwAAAAAAAIyAYA0AAAAAAAAwAoI1AAAAAAAAwAgI1gAAAAAAAAAjIFgDAAAAAAAAjGAuwfprP7yACywAAAAAAADk44bT/+8DNVYpzOHiKH1miIiIiIiIOB9vOPPhmkJERERERETE2bzh7No5hYiIiIiIiIizecNHH59XiIiIiIiIiDibN6ytX1CIiIiIiIiIOJsEa0RERERERMQREqwRERERERERR0iwRkRERERERBwhwRoRERERERFxhARrRERERERExBESrBERERERERFHSLBGREREREREHCHBGhEREREREXGEBGtERERERETEERKsEREREREREUdIsEZEREREREQcIcEaERERERERcYQEa0RERERERMQREqwRERERERERR0iwRkRERERERBwhwRoRERERERFxhARrRERERERExBESrBERERERERFHSLBGREREREREHOFcgvXJkycRMXBtbc0IAG3K74fUpqQIAAAAsAgQrBEzSbAGiEOwBgAAgClBsEbMJMEaIA7BGgAAAKYEwRoxkwRrgDgEawAAAJgSBGvETBKsAeIQrAEAAGBKEKwRM0mwBohDsAYAAIApQbBGzCTBGiAOwRoAAACmBMEaMZMEa4A4BGsAAACYEgRrxEwSrAHiEKwBAABgShCsETNJsAaIQ7AGAACAKUGwRswkwRogDsEaAAAApgTBGjGTBGuAOARrAAAAmBIEa1QnD6+pP/jhefXDw8I831+sq689uqYOSfOwJcFa4NxhteuRw+q8ezkIvc72vWrVvDitVgasv/rcfWrXoYvm39tjy5/aq26vtlugX6eWreKi2v9Isa/tT6j959wk6IRgDQAAAFOCYJ1LE1bX1Up03gV17y+Eecb31Q8fvaC+Viwz2Cc/dOt+qO6V5vuG4TgI1itPCusM8A+efb/eJhKsI5iwawJtEZK36/+H2nBahuNGsD5XBNiusOyo1nX/v/250+b/NXbfK6fcS4MLx61l+7Hv6Qm1a8b1tyIEawAAAJgSBOtcdgXrwkPPnu8Y/bXBelhQdSG8CtbteVKAN/sv12HEOosE6xg2wO46dLgdbk2I7gjWhv4A7AdrifOHngjCfJ/+/pvYbZXzy/cW3zdYCNYAAAAwJQjWuWwE6wGjyNoqHM8pWHcEYYJ1fgnWfdSjxiac6qA8KFgXnLtoRqxTAnIVds0t4MW0MJh7+x6KGalujZ4TrodAsAYAAIApQbCetyakBoG5DKNiMNWhOwy18wnW4i3dbv+dwVp6D30SuFsSrENs4KxHqEcE6x6iI9Zu+yvPpY1YN28Z19iyd4VnE7q5LTwKwRoAAACmBME6l40R69pGoHUj2e1btecQrIX9+/tmxDq/BGsBN1psg2pqsLbL27DbPbJcba9BHezF+d6+uzCBuSjPivm325Xn9PtNGwXfKhCsAQAAYEoQrHPpBVsTYsMRXtEyCI8P1nq0urm+Xa4M8QTr/BKsI1R/jXvGEesBAVgO1jVmfhCCu7QXAma9xZtbwyUI1gAAADAlCNa5NGHVBubmiHRkhLnhyGAtBWA9zRvBjgZrr9zJErobEqz7GB+s5YC8V+0fEqxnHLGG+UCwBgAAgClBsJ63JsCWYbN9K/iw0eExwbp+Zjt8xtrfXuqItVn+0XV176MDRrbRSLDuY44j1uEyPb9JnTpiHd7ObW8HHyJBPQbBGgAAAKYEwTqXJqzaYD34d6GrEd8RwboI9uF6Zv/BaHJKsLbldxcJWqPhwog5GgnWEaoQXAfrZoieQ7AOXw+g2t8ATLDuGBG36PdHsI5BsAYAAIApQbDOpResy2kmoAYB1I4Eh7dQjxmxbmq2L4TmYcG6/Jmw5jxb5vPFOnqeu9X98PvcBh5IsI5QPWNdUgdsnyHB+vyhw3Z6K0jLoTZ9pLrWLx/BejwEawAAAJgSBOtchsG6cYu4DaONkeCG8wnWdvsDbt0WgrVdV293Xfg5MPkiATYlWMu0Qmn5u9KxEBoL1oe8v7jdCtbNn/YSn6l2mPIU6+q/8r3rub3FdtohP4RgPR6CNQAAAEwJgnUuhRHrSiFkN5dxYdlbptdGyJVHmqP6ZS3LVm2v+TvbdgS8ueywCwBbT4K1RPBb1iYQu9cmYAtBVAzWOgy3t1OOLuuRbj9MV6PfFXaU3N+Gv4wN24WR57QJ1uNZlmDt17MAAAAAMQjW89aEVNcRM+G0DLmewUhvPTpcTh83Ym221/cXuoNwH5ap1gbre5/UgVoukw3bejuRCwlbVIK1gB+S3Uh1Y3RYCtfhrePeelUALmw/H10G2zLM23/t8v7otqUdvgv8wO4FaX+/3RKsYxCsAQAAYEoQrBfS+dwKPhcZlZ5ZgrWADsU6oEoB2lGONMdC8/li3ZVWiI5QBeN2kB4DI9bjIVgDAADAlCBYI2aSYA0Qh2ANAAAAU4JgjZhJgjVAHII1AAAATAmCNWImCdYAcbZqsD76+B3qllvvUN958SM3BaCb8pzZfcxNANgKHPuxOe9veZwTH5YHgjViJgnWAHG2YrBef/EB21E0/lgdddOHYgNW+npNjqndvcHeLrOZQc4eq9h7HfIeJkIZLrQP7FPrbvIs2GP6gHp+QLOUsqzPrOtNn4/U8w+0P0PznZ75c7Xfg2kGT/fejJxPsDwQrBEzSbAGiLPlgnVj9GWWDvFHan2tYz0/gIU2Ou4DQulaEQKGhPiufQ6wK7gTrDXu89afnzvWYy52EKwl3DEea+M7KX1PpWned7o1bwjSNqeBvYioz6PpvkeYJgRrxEwSrAHibKlgvbZPfUd3Dv2A66Z1hcPyFuBeo8Er3sGv9+tG0spt9eqFJrfP1IBrw9cmBuuzxbG/7e5i/5fdhMvqzK/2qPvv+abaZt7jXerO7+5Wz79dzm/y2bsvq93fu1t9wy274+Gn1RHvr/+fKcq+bUdR9s/dhJkoP5f6eM90x8LIix+1w/a72cG68Z0pv2/mGLjyu+9d17nXPYrcf+6Jx6Dv+z7ThZNcoXO+34dUyvqhOlYzHRtHx2ffrF8Tv1cAEQjWiJkkWAPE2TLBugw2Uud3QLi2y0idPt2pbodcv/Mph5xYMNBBLhaI9DpCGdw+O8svUHac67KmhvuI0TDkcc3u686f1j/At/5SUZ7bvqm+8/g+dfA3r6sjv9qndv/Xu4pt+uHb8lnxnu8s9nXn955W+/Syrzyt7t9R7FsH6StuoeL97HuwCCN7jqnP3JRUyk5/M0y44zTkfQqkhN6UZX1mXW9emOP26AF18ZPL6uIld2WjI1xJjAvWkbArfD/HE9nXSOb/fUjAHafwPc18XnV99leKc6Q4T1Z/fl+9DMBICNaImSRYA8TZCsG6DJCdHV/X2Ysv48JUX0ez1XFvdrqrsoR6ASIWKOSQV+D2OT5Yt7HLxDq7feEmzsX9P1Dbbtutjnijyeu/OaCOXnIvSq6tqid0QPCPh5u2befLav2am6Y5+4L5DP/9U96v5b/3rNpx6x+pZ8641wlEj7fBfa4zhOvWOdNBfFm3/zF2fR9GYo5duP2ucCUwKliXwXCsbv/R7+1g08Nolu/DEMpjFzk/7Pci8f0M+Oy76xqANAjWiJkkWAPEmXawrkdguzrwNWVYiXTuTOfQ61C6DmKjc+86peX+4p3FrmBg5zXK3BVE3D6XJ1i/r5759h1qxwvvu9fd2I68V4bi/W679ZvqiVZe+Fwd/Kti2e17VD3rvNr3Z6nhojxv+sKDO18Sw3V6SIsH69ixt/uIlV++SGRw59LYgLPpwVrEfV4zXFAY8j2Ibte878Qg2sG470M35bnZd1yTw/WAz777GAOkQbBGzCTBGiDOZIN1GRASQ48m3rm0gaScLnb83X5Np1EK3hUDglHVUe8IQhq3z77OcEj5Pjc8WL/3rNp+673qmffc6x7Mcb6tLsM7P7+3KNNudVB4dtqWt9nh16PjZn1/NC+G+8yGd/DLED48EEhljBFfdsD5E93HJgXrRMTvV0X6uZdy3EPsurFjkhasPzuub9u+S93/SuL3xjH2+yBTnsfd9YGP3fbw5fvoPsYAaRCsETNJsAaIM8Vg3ehMVkEhQdNBdp3lB/5G7QznRy32+aIXrMt9i+GgGQxMZ7nazjCrULFkwdo8Ozp0FE3f5rr9DrXt0deq56TNsfrWs+od97qBORZ3qceOu9caE5a/qZ54272OUB4POSC54BEJeuW6Q45F4/zsIb5s97Hv3kfPhZo5sHjBug6OgwzKbo/nAgTreXwfQnouJnWeS+W60c9pON3HGCANgjViJgnWAHGmGKz76Q5Jo3Ahtwqr7nV7X2Uw2Ff8K3VaE8KP28eyBGsTBHYeUBfd6ziXi2XvVrfcVhyfs25S32cXHn+DK+dL593rNqZMnZ36IefMsPOqPO7Dlc6P7mPfGYZSzq0ZSQvWrjyt9z2b4jEx50VxPPSFr67PJ/JdGvI9GBqsZ2de3wePvvkF3eeSZcgyfXQfY4A0CNaIiLhpSm1KirlZ2mBdYDuMfmfddcSNckcyqaMaCQN9lOXa2GB9Wb2ysyOElFz7SB18VIeIe9Vjjb+APEuQsOukHp8m8ztnUj7b+LJTCtYyZhvR451y7vmfnV6v57gI5/uQ70HWYD3X70MaKefrGLqPMUAaBGtERNw0pTYlxdxsdrC2I5odltvqCHZ6mQPVyKgfDMoOfZpVqJhTsC5fz8VoqHLvtSt0nXlZPXTPXWrbPY+pg63OvPuDTPe9oMQ/9G2ORXjbt91n6vFpkn7OxEgJKvFlXZgb4zIE6+g2EoJ1EGzNMZU+x47v0fjvxohgOvfvQxop5+sY7H4I1jAfCNaIiLhpSm1KirmZLVjPHj7CznXX6FljnuuchyNE7c5pLBi4MguBwoZ7oePZEQi6KMPCmNGsdM6rfQ/K709z8c0fq+233aV27Hm9+dNBHkf36N/yfUwdEeab57dv/YF6pfEzRdMN1rH31L2PARc3RjI+WPeVcWiwlpYTtt3zrLA9nhs/Yp3n+5BGyvk6hu5jDJAGwRoRETdNqU1JMTezBesY6SFpbLBud67lYBANz67jL4bgzMFal0laRk9P3afGvMe/qv/4UsXbe9Sdt96tHtrfvc3Pjuwuyi39VXE3evftcPTumHrstqKsHc9Y9zMuWNvPdT4OOeYbFYZimPc7Klj3BedhwdqUQ/rM3PfJru+C8cyhridYz0q270MaBGtYRgjWiIi4aUptSoq5WfZg3e40CsGg6Ow//7hd3+o6s+VoWueI2LDA5dMfrMvA4b2/krJMxrTOsPxXwe3vTd/yowPtwB3y+WtqVxGUt4Xh/OwLpkz3vxIE6HO6rONuhx0brDeapQ/WrQtRIf3BuvcYuO+NdcyxyhGsM34fEtmoc6ldRwLMDsEaERE3TalNSTE3yx2s3f4aHe/+YGC2azr98X0bGgEhXTFYe9scWsbBwd78jvUfqWf8YbRrr5vjsf2vX1ZHfvO66NGz9Q/16nC+7da71PadT6t9ev4re9S9dxTh4sF96kxwS6wZ0btttzoi/M7vcBLPmUsH1P8o3s+uzp1K54VmfFCbOQxVn/u4gDMuWA95/93fn/737469ea/W+AWmPtI+r0E/t5Xx+5AKwRqWEYI1IiJumlKbkmJuli5Yv+iP6BZGwlM0jDZGhGvF5d0+Bwdbh+3IRi4CmP0N7Ez7ZR10TN9Xz3z7DrXjhffd64LI+/UN39/6m3vU/Tv086XF/DvuVvc/JT2Hakf+/N/9nY3Ec6b4TLZ1PNtaXpAQP7O1j8w+ys9nlrAxcxja9GDtQmrvce74/pj3EH/v5bH3l6mO9ZgyzzNYZ/s+pDPzuZSI3Q/BGuYDwRoRETdNqU1JMTdpwbo9GjWbdWey7oxHDIN1Xx/bdZxbneMqTBWGHfUq9ASdXDddDBkdlPsqy9q5717SAvnF/T9Q27YXnehRo8gDeO9ZtUOPjreeP00lLVi/8/N7hd/qdgGsMOmzmiHsblQYijFTsC7f56Bj3HNhqkV97LuOS/U9H3oBxZAWrJeNjTqX7H4I1jAfCNaIiLhpSm1KirlJC9bzx3S4I53txry+YF2FJK3rRPqjU0M65337mBkdEMZ1oHXneFDYuWaD6p0/bT5pPV8+UvsevEvduefYyNFqTUqwtr/V7R8HG9hGhpOEz30hgvWjB9TFTy6ri5f6r57Y8qac00ODtXfBJyH4pgVsgvUorhTnSHGerP78vmI/BGuYDwRrRETcNKU2JcXcTCZYQ83Zfeo7t91dHKvLbsJ8OVMEgm07NmBUPMQ8H7t5oXYRqILp4HAKW5XGuUKwhjlBsEZExE1TalNSzM1mB2sAAABYDgjWiIi4aUptSoq5IVgDAADAEBYmWK+urhqPHz+u3nrrLUTETp/71dvq9//nmvr6j+rgg/nVx1sf9+ePvCPW5alKbUqKufHfOwAAAECMhQjWZaA+d+6cun79uisaAIDMG2evqa//RTPw4caqA/Y8wrXUpqSYG/89AwAAAMRYmGCtQzUAwBD+8KeXGoEHN0c9ci3V6SlKbUqKAAAAAIvAQgRrPVrNSDUADIXR6sVQj1pLdXqKUpuSIgAAAMAisBDBWj8vCQAwFCnk4eYo1ekpSm1KigAAAACLAMEaAJYOKeDh5ijV6SlKbUqKAAAAAIsAwRoAlg4p4OHmKNXpKUptSooAAAAAiwDBGgCWDing4eYo1ekpSm1KigAAAACLAMEaAJYOKeDh5ijV6SlKbUqKAAAAAIsAwRoAlg4p4OHmKNXpKUptSooAAAAAi8DyBetLJ9XP9p5Ul91Lpa6o3+59Uv3stSPB9C7W1MG/PKLOuFd9nHntSXXwA/0/va+X1G8vmckCertFWU5csS/Dsn5wRP35oP0W25HeS+u911w+8VKx7Sd7te+jjVl/8PED2FykgJfsztPqxu+eVDc9bF/f/P03i9cxT6ubq3XX1U0P1uvN5EMn1Y3fPyvPE9Rlu2mn/n/fvs+qm4ryfvWhdfv64TPqqw+eqeeb9+y/l/FKdXqKUpuSIgAAAMAisNzB2gRVF2TN9CNFIC1DZBlgbdj1w2VcIfTqfYThOBZAL11Rl3U5im2ZACuU9eAHehk9oYtIsHYXEaRwrINxLDSXRJcxZeu6YACwWEgBL9lj+rfzv1Sv7rWh9Sfrdtsy19VPqnU/Va9eva5efdnbVqIPvPelUh9/UgfgLosw/OSaUqvH9OsrZt+//DsvLPs+fFWtFqW98PYZG8Rf/kxduPqZekDP06H611eLudfUT8ZcFAiU6vQUpTYlRQAAAIBFYKmCtR45rkNwEQRPHImMDusA2jUyPHTEWi8XBk43Ql7ut4tGmfrwy+QFaxfIY5blmDlY92xfK7/XurxmtLuxTnhs9bL+duwxbK5jtcv4x8Ij6XjClJEC3mx+boKoDa3Oh894QVYyEqz1KHRjlNuNLOtR48Z065++fc0E4Ob0cDT6rLrp158rdfULG461x64Vry+p/yaF8leuqAde+ULpuGnK7wdrcyFBT9fLeOuMVKrTU5TalBQBAAAAFoFJjFhrD56w089UIc8FswHB0bcOnvHR4TIo+vPa4bJbMeC+thZcPHBBUwiUejk/8M4SrMt9ycG5QJcpFmRdeTV6u2FZ/PXM/Nit+vq9iUGcYA1xpICXqrn1u7wd29wi7cLt3kvqwpVL6k+lwGvC8xn1yyvX1C/3Nuc98K4NrjUufLugO4wv1atV6NW3fa+rE41pWj1q7Y1Kl9Nbwb5QfC/WxrojlOr0FKU2JUUAAACARWDpg3UV6Bqhyxux9pcpqJ+XLtDh0BuRrueFI6wSdpkyXIaYbZmwX4TKjuUsurz+yHix7TBAeu8jDLKaMDRL+MuY8OtffAjKZ0J3tMzN8rbL4wfjctnwPToI1jADUsBL1dz6/fEn6kb9DLIbzY1jw625hbtFEaD1vCJYn/iHcvt9t4vr+Z+rPeI8rX5WugjwRYCWR87tSPuJXxch2V0ckMsWJz4in6ZUp6cotSkpAgAAACwCSxusf/taEdJO6GBsR13bBsHMhOhgmUhI06HSjLCGywfqkGoCaLUdF7bdvCo0mn+b6zVoBcYyWOswWq8n6tZLDdYhVdB2x6lzW0F5O4O1t6zZRxjWy2PkXloI1tCNFPBm0YTR6jbrdXXT311SF9zz1Dp4n/i19Ie+/NBcB+R5Buubv69Hqu2odDjSXGuXUR+v24sDZl37x8v0/D1F+VdPf6YuXLluR8zXiuXcvHmNVmulOj1FqU1JEQAAAGARWLJgXQfN/nAaw4bfcn0TojtHpqWRVlsOvwwmYIdhUCqTCZLNfep1m++nDOj+9prlDhkbrMtydY+sW8LyhsHaHAu3ncbxNfsQjpEYrO3n3JJgDQVSwBunP0Ks/68DtR4V/kI92XruOT1Yt//iuL6d/Gqx7WC6G33Wof7CugvEHej9mZF3fXHA7OOSDdsF1TPWxXv4SXA7uh7pHvSH0wYo1ekpSm1KigAAAACLwFIFaxNwP6jDqhkBlcJXYTssl6HchjgbhH3DcFcijZ7GgvVw6/L5268vHNgA2REwS12AnTVYdx3D0uaxbB+P1jaqcK6XbV6UCEN5PFgLn4delmANBVLAm0n9bPX3z7hnmYsw+96VYvqV4v9uNNkE0vovh9v1LqpXrxSh2Tz3PCxYd//FcY/1z936vv7+SvX2bbAup+35WG8gCOvSM9Z6WrHkhXc/9bY3u1KdnqLUpqQIAAAAsAgs9zPWBTrUtYNfOMIsBVRpGSHMCc8fy6PYITYkm2esWyHfQ9x+URY/QLaWaZc1NViXFwJ0+dr7r2kdX6G87c/A4W4rb+m/N4I1zIAU8Gbx5jeKdLr+hQmpq0f1X+/WI9UuWD90Un31oSJ0f/cTE7qrZ5J36lHhL9zPb+nQ2x+s29aBXJ7vafZ3zfu5L60L1kfraYPDu8NeRPC3OZtSnZ6i1KakCAAAALAILH2w1lS3G5uQFgu8OqyV8+pgrENh/PZivY50+7W/LRkTXF0ArcrXIhbQi+1XZfJGsc0+5TKlBusKMdjXNEOzXF45WNty9x47gjXMgBTw0l1Xe4pT/4QLzDe/qEdydYC1wfrV09fVhXc+U6uq+bvRJoxXz2XXo9t5grX+uS0d/sORbDeKHd2+vv3c3tp+4eqX6sK7Z+Z263eoVKenKLUpKQIAAAAsApMI1v7IqBQuTXhuzAsCYrl+Y7s2wMZHYoXgV1COBEujunp6Y3vRoOgH65pq2x3b71MM1sJyvlWZI+UVg7UYmC3+RQd5OYI1dCMFvGQf/qQInm7k2f12deNWcH0buP696H+4Xv9u9M7T3nJ6vU+r0WsTrPVf6Ta3XOtnqMcGa/2st71FvfUXvM0odnh7uLV8nvtJfWu4C+Tmme1318z0eQdsqU5PUWpTUgQAAABYBJYqWFfhUYcyPxB6ITMMn+0Q5+bFgmu17ebIbBhcm0HSG1X2yiJRbafY/6lif2HQrcqvt+OXt7CxrHv/ZTn0dqWLCj7iMno7HWXW65T70GXr2wfARiAFvGRf+rQIzm7k2TxLfU3tMaFYh1kdlu3vRetQa4Lpe5+qm14vJui/Gl7+7rV+XtltQwfrJjZYt/9wmTbyx8u0+g+Yme3bW9CrEO//TrUexW7cHq5/89rOM4FaE4xylz/HVQbs+i+Jj1Oq01OU2pQUAQAAABaB7MH6g8cfU9f/xe8odeM/Uup3v1Ko/0VEzGBRz1z65/9Mfe/f/XcxBPrqoNl8ztj+NrShutXbtw7a/u9el9vQ26tHlvWy9revU599NoHYbN+uX+4//J3qZtlt2QziH0CrrbYjvsd0pXo/RalNSXEjuHr1qrpw4YJaX19HREREFM0arHWoVjcSphFxo/2K+stb/4sYBHG+SnV/ilKbkmJudKiWGk9ERERE36zB+svf+6dChxcRMb/Xf/cfi0EQ56tU96cotSkp5oaRakRERBxi1mDtd3LPfes/q/976KC4XNIfLwOALY8U8LR/+K0XGvWOtAzOV6lOT1FqU1LMjdRwIiIiIobmDdbmuWrr27/5tbiMlmANAClIAa+0/lsOXxHn43yV6vQUpTYlxdxIDSciIiJi6IaNWEvzSwnWAJCCFPBK/XpHmo/zVarTU5TalBRzIzWciIiIiKELEayPHz+url8Pf6oGAEDm638hhzytX+9I83F+/t6Pzot1eopSm5JibqSGExERETF0IYL16uqqOnfunOvGAAB082//9ydi0NP69Y40H+fnv/6bs2KdnqLUpqSYG6nhRERERAxdmGCtR611uGbkGgD6OPjOxeiotV/vSPNxPurR6v+z/7hYp6cotSkp5kZqOBERERFDFyJYa3W4LgO2fuYaETHmG2+8oZ7+5TEzYqoDnh/4/HrHn47zUR9vfdz/dv9b6ujRo2J9nqLUpqSYG6nhRERERAxdmGCNiDjUEydOqDfffNME7FC/3pHm43zUx19/DtLnk6LUpqSYG6nhRERERAwlWCPiUqpDnR4xDQO2X+/403E+6uOtj/s8QrVWalNSzI3UcCIiIiKGEqwRcVJS7yyXUpuSYm6khhMRERExlGCNiJOSeme5lNqUFHMjNZyIiIiIoQRrRJyU1DvLpdSmpJgbqeFEREREDCVYI+KkpN5ZLqU2JcXcSA0nIiIiYijBGhEnJfXOcim1KSnmRmo4EREREUMJ1og4Kal3lkupTUkxN1LDiYiIiBhKsEbESUm9s1xKbUqKuZEaTkRERMRQgjUiTkrqneVSalNSzI3UcCIiIiKGEqwRcVJS7yyXUpuSYm6khjPu36udf7yiToXTT66oe6TphadW/kT9y2/c3uvOg+11q/Uj2267qp76Y397RXm/8Yg6IC6LW8uNOHf1+ebP+xP11Ek778Du+Dlu1educa7q8jS24bn774X1EHG53Ph2tK5/dD1T10ttbR12z8qqfR2W6eAjBGtEnJbUO8ul1KakmJtmo9pnpEPgAq3UqOsOQXeg6FimaMT9cBLT73T429HTqw4CbnE34tz19+F1YM15HHaC/Qs+8TIYXdjuKwsiLoOb0I4G4Th6sfrkqjrl1zd+sHb12FyCdRSvgwsAsCFQ7ywVUpuSYm5aDWunXodADAu1ZaCduUPQs31tGJqbo4K2kzJkPdwKbsS5KwXrYprerjfarNepX9vzNHpOEqoRJ+YGtqN6X62L0z11jm84Yl1IsAaAaUG9s1RIbUqKuWk0oh3q0Npq8IVGVy/nN9izdAjKfUUbft0ZCfarbQRrvUzr1tn4iABO1407d12Irizm7bZ3TVTnZnDu6vXLfYb706/tdnicAXEKblxdpO1q72xdJdc33RKsAWBaUO8sFVKbkmJumo1tn96V9tIiKPjBwO8MlNNSOgS2cXdBQgjHpmPSmGY7D+0OQBlG9HzvllwhkONWMP+5W+1D6CjXoTsSkv119Hmqly3Pcz3Pf42IS+wG1UVFnRFup6mrkyL1irkYuKLrpaI83nIEawCYFtQ7S4XUpqSYm7Ax7bbsEMTCrKfrOKR3CNrzTBhxYSO+LVsm0wlodCa8YN1YHreWG3jutoJ13YEtR6ya67hz9GB3gDbfhcZ2EXH5zF8XmRHv3UVYl7bpqZc3dVJVr7i6ys2zF/WK9re8uFdIsAaAaUG9s1RIbUqKuQkb527LRtcfdbPTYo3+zOGkdOhonQ4lRSdFb+fUyiNFkC4DtR9aCNhb1404d/X2mp1Qq79PretQu3NabyM6ko2IE3Oj29GyLQynNfdnL/oF9VDrIiEj1gAwNah3lgqpTUkxN1UD2qkLArozYBrZsmPQoRcaZukQ2LAhbNezHpkuyrd7pdDrKFS3fdedCrPNvoCOE3Mjz10vWFedUW//wj7seapvtXQd2vI2cFEuDCEurxvfjlpdvdSYZsviL1/eTdMnwRoApgX1zlIhtSkp5qZuaIdYNNBVYCjUIaARVNsNeGqHoGzc9S3dXSFYr+M/k6bX1+va7fidBv3/MpC0OxO4Vcx/7lbbaAXrIBBX+9bz9D7b+zYKo0WIuOxuRF3k2dq+VqiXWtr2Mny8imANANOCemepkNqUFHPTbEj79DsEttG1V7F1A607A+3QOnOHQOwM1Op1ysb+wG7bCSmDtZ5Xrxt0IPR2CStb0I04d12HeHCwLqe59arXToI14gTdiLqoVN6enR7US4HmIrerp/T/y/aWYA0A04J6Z6mQ2pQUc+M3pP36HYLacpTZGIRhE3LLeR22Gn4dPoTlfP2r6Np6xNpXCDa4Bd2Ic1d3Vh9RT3nr7Tzod5w9CdaIW9SNakd1vdJuJ42mfRXqnMKqHJEyEKwBYFpQ7ywVUpuSYm78hrPLRmOrO/z6/85GY+4CcdmYy1fRm4rLtEb1mup1uoO1F2gIJ1vajTp3y/00z8uEEeugbKKcy4hL64a1o2b9Zr2j55f78rdt9drLjnZXS7AGgGlBvbNUSG1KirmRGk5ERETEUII1AEwL6p2lQmpTUsyN1HAiIiIihhKsAWBaUO8sFVKbkmJupIYTERERMZRgDQDTgnpnqZDalBRzIzWciIiIiKEEawCYFtQ7S4XUpqSYG6nhRERERAwlWAPAtKDeWSqkNiXF3EgNJyIiImIowVri3GG1a/t9atehi25CjItq/yPhcqfVSrHu7Z71/GLeI4fVefeqQu9Pml5w/tATjW3FXDnlVgDY6ixrvbNFkdqUFHMjNZyIiIiIoUsdrI8df7vhfLDBeOWU/vcJtf+cm+zRFXbtenvVqlt29Tk/9EaCtQvoUjjW++oLzUOWAdgyZK53YL5IbUqKuZEaTkRERMTQpQ3WOkg/+IO/bvijR/6XmzsrwQi0GbmuQ7KPDrP+SHX92gvWp/aq2587rf/n8IK1nicE89Jy2wRrgEQy1jswf6Q2JcXcSA0nIiIiYujSB2sfHay1f/uzX7T8aE0YevaJ3f5tpssj19VodBGS6/XKYK1Der2eXrYVnIVbwPVyfhkI1gCJZKx3YP5IbUqKuZEaTkRERMTQSQVrjRSq9XJdt4rrYHp7JDxbdFguArEZfbaj2n5I9t116LAN1i6oNwOvcCu4F8p1OcJgT7AGSCRjvQPzR2pTUsyN1HAiIiIihk4uWEt0BWszklwE5nBEuWURiFd1ABefkfbxbgU3//cDexmsu8O50e2HYA2QSMZ6B+aP1KakmBup4UREREQM3fLBWsYPx6kE6zaes9bzdHD2t22nxYIxwRogkYz1DswfqU1JMTdSw4mIiIgYSrAW6QvWkRFnE6CDdfUt4c+9VS9vRqLLgN2hC+MEa4BEMtY7MH+kNiXF3EgNJyIiImIowVrjnocWA65nHV6bf5jMUI1MB8E6HLH2byVvzNO0Az3BGiCRjPUOzB+pTUkxN1LDiYiIiBhKsBZpB9wm/cF6pXpm29+OH6z9UW+9Lb1e+5ZwgjVAIhnrHZg/UpuSYm6khhMRERExdOmD9VDnH6zLUOwpjVg38IN1TeMPpzVGsG1obuwjIsEawJGx3oH5I7UpKeZGajgRERERQ5c2WGt0WB5qFD3SLATVmPbnsBJuBXdU4VkvE9x63gjFrjz+T3AxYg2QQOZ6B+aL1KakmBup4UREREQMzR+sb6SDCwAbCPXOUiG1KSnmRmo4EREREUM3bsT69DtuIgBAJq5ebdY7sPBIbUqKufnwww8RERERe80brG/6J14n9yve/xERcxjUM7DwSG1Kirn59DoiIiJiv3mD9bf+U7OTi4i4Uf6bf+UqIlhkpDYlxdxIDSciIiJiaN5grfmP/8Hr7DJqjYi5LeqZ37/FVUCw6EhtSoq5kRpORERExND8wRoAACCC1KakmBup4UREREQMJVgDAMCmIbUpKeZGajgRERERQwnWAACwaUhtSoq5kRpORERExFCCNQAAbBpSm5JibqSGExERETGUYA0AAJuG1KakmBup4URERERsqtT/B4h5fkcaUuxRAAAAAElFTkSuQmCC)

**Comment by xian-crazy** [comment]
用例集合新版本已经增加用例数统计
用例集合暂时不会支持单独的【全部用例】节点，意义不大
必须使用的情况下，可以自己建立一个【全部用例】的根目录，把其他用例集合都移动到这个节点下，然后勾选【包含子用例】即可
