### ISSUE TITLE
更新版本后，参数变量解析异常

### ISSUE THREAD

**Issue by hardBeasy** [xian-crazy/yapi#66]
## 版本号
~ 
当前最新
## 什么问题
body参数，json内包含动态参数（双花括号解析）：
![image](https://user-images.githubusercontent.com/49235727/69520923-ce5f0200-0f98-11ea-9af0-ec3261a54c4e.png)

请求时仅某个成功，降版本回滚代码可全部成功，console如下：
![image](https://user-images.githubusercontent.com/49235727/69520886-b0919d00-0f98-11ea-85e5-cc934ad2f915.png)

## 如何复现此问题
~ 

## 什么浏览器
~

**Comment by hardBeasy** [comment]
@BetaGo 烦请老师排查，感谢~

**Comment by hardBeasy** [comment]
{{$.key.body}}  可解析到object，再追加data就会解析为字符串

**Comment by BetaGo** [comment]
这个我这里目前没法复现，可否提供一个更准确的复现用例？

**Comment by hardBeasy** [comment]
@BetaGo 
用例1接口返回：
{
  "status": 0,
  "statusText": "Success",
  "data": "ssssssssssssssss"
}
用例2请求入参变量只到body.data即可复现：
{
  "sql": "{{$.5043.body.data}}",
  "server": "456"
}

**Comment by BetaGo** [comment]
@hardBeasy 
我重新部署了代码，并尝试了
`{{{$.17654.body.data}}`
`{{$.17603.body.data._id}}`
`{{$.17603.body.data.cat[0]._id}}`
等写法，都是可以成功的；

先检查一下在用例的后置处理器中是否有对responseData有修改，导致responseData.data被设置为了`{{$.5043.body.data}}`这样的字符串。

如果没有，请提供一下 这两个版本的版本号或 commit id，我看下之间代码有啥差异可能会导致问题。

**Comment by hardBeasy** [comment]
@BetaGo 确认无后置处理器操作，且切换版本后立即运行即可成功。在示例工程中创建了测试集（个人空间>项目A），请在此测试集中查看用例1_2,2_2结果即可（http://crazy-yapi.camdy.cn/project/34/interface/col/66，账号805675496@qq.com,您可以重置账号密码，使用结束后邮件回复我密码即可~感谢~）
